# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import pymongo
db_client = pymongo.MongoClient("mongodb://mongo:pnMPibl9MybIhP32sg7r@containers-us-west-207.railway.app:6059/")
current_db = db_client["MusicService"]
collection = current_db["song"]

from PyQt5 import QtCore, QtGui, QtWidgets
from matplotlib import pyplot as plt
from Umusician import Ui_UMForm
from auth import Ui_AForm

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(471, 388)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.MButton = QtWidgets.QPushButton(self.centralwidget)
        self.MButton.setObjectName("MButton")
        self.gridLayout.addWidget(self.MButton, 0, 0, 1, 1)
        self.AButton = QtWidgets.QPushButton(self.centralwidget)
        self.AButton.setObjectName("AButton")
        self.gridLayout.addWidget(self.AButton, 1, 0, 1, 1)
        self.SButton = QtWidgets.QPushButton(self.centralwidget)
        self.SButton.setObjectName("SButton")
        self.gridLayout.addWidget(self.SButton, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 471, 18))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menu.addSeparator()
        self.menubar.addAction(self.menu.menuAction())
        self.AButton.clicked.connect(self.Ascr)
        self.SButton.clicked.connect(self.Sscr)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.MButton.clicked.connect(self.Mscr)
    def Mscr(self):
        self.UMForm = QtWidgets.QWidget()
        self.ui = Ui_UMForm()
        self.ui.setupUi(self.UMForm)
        self.UMForm.show()

    def Ascr(self):
        self.AForm = QtWidgets.QWidget()
        self.ui = Ui_AForm()
        self.ui.setupUi(self.AForm)
        self.AForm.show()

    def seconds(self):
        collection = current_db['song']
        cursor = collection.find({}, {'song_duration'})
        res = []
        for document in cursor:
            min, sec = document['song_duration'].split(':')
            res.append(int(min) * 60 + int(sec))
        return res

    def Sscr(self):
        secs = self.seconds()
        bins = [60, 120, 180, 240, 300, 360]
        plt.hist(secs, bins=bins, edgecolor='black')
        plt.tight_layout()
        plt.show()


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Музыкальный сервис"))
        self.MButton.setText(_translate("MainWindow", "Пользователь"))
        self.AButton.setText(_translate("MainWindow", "Доступ администратора"))
        self.SButton.setText(_translate("MainWindow", "Статистика"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
